//front-end
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import styles from '../styles/Home.module.css'
import Button from '@material-tailwind/react/Button'
import Icon from '@material-tailwind/react/Icon'
import Sidebar from '../components/sidebar/Sidebar'
import Widgets from '../components/widgets/Widgets'
import BlogPost from '../components/feed/BlogPost'
//modal
import Modal from '@material-tailwind/react/Modal'
import ModalHeader from '@material-tailwind/react/ModalHeader'
import ModalBody from '@material-tailwind/react/ModalBody'
import ModalFooter from '@material-tailwind/react/ModalFooter'
import Input from '@material-tailwind/react/Input'
//back-end
import { useAuthState } from 'react-firebase-hooks/auth'
import { useCollection } from 'react-firebase-hooks/firestore'
import { creds, store } from '../firebaseFile'

export default function Home () {
  const [user] = useAuthState(creds)

  const [docsSnapshot] = useCollection(
    store.collection('blogPosts').orderBy('timestamp', 'desc')
  )

  return (
    <>
      <div className='scrollbar-hide h-screen overflow-hidden pb-[120px] bg-gray-200'>
        <Head>
          <title>Blog-Dev</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Header />
        <div className='indexMainDiv'>
          <Sidebar />
          <main
            className='
          flex-[0.8]
      bg-teal-100 
      mx-auto
      place-items-center
      justify-center 
      scrollbar-hide 
      overflow-y-scroll 
      h-screen 
      border-x-2
      border-blue-400
      pb-[320px]'
          >
            <div
              className='
          bg-cover
          bg-gray-200
          flex-1
          opacity-80
          p-[190px]
          lg:p-[260px]
        bg-mm-lakes
        grid
        place-items-center
        '
            />

            <div className='h-screen grid-cols-1 lg:grid-cols-3 pb-8'>
              {docsSnapshot?.docs.map(doc => (
                <BlogPost
                  key={doc.id}
                  id={doc.id}
                  title={doc.data().title}
                  author={doc.data().author}
                  blogContent={doc.data().blogContent}
                />
              ))}
            </div>
          </main>
        </div>
      </div>
    </>
  )
}
