//front-end
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import styles from '../styles/Home.module.css'
import Button from '@material-tailwind/react/Button'
import Icon from '@material-tailwind/react/Icon'
import Sidebar from '../components/sidebar/Sidebar'
import Widgets from '../components/widgets/Widgets'
import BlogPost from '../components/feed/BlogPost'
//modal
import Modal from '@material-tailwind/react/Modal'
import ModalHeader from '@material-tailwind/react/ModalHeader'
import ModalBody from '@material-tailwind/react/ModalBody'
import ModalFooter from '@material-tailwind/react/ModalFooter'
//back-end

export default function Home () {
  return (
    <div className='scrollbar-hide h-screen overflow-hidden pb-10 bg-gray-200'>
      <Head>
        <title>Blog-Dev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <div className='flex max-w-[1780px] mx-auto items-center'>
        <Sidebar />
        <main
          className='
          flex-[0.8]
      bg-teal-100 
      mx-auto
      place-items-center
      justify-center 
      scrollbar-hide 
      overflow-y-scroll 
      h-screen 
      border-x-2
      border-blue-400
      pb-32'
        >
          <div
            className='
          bg-cover
          bg-gray-200
          flex-1
          opacity-80
          p-[190px]
          lg:p-[260px]
        bg-mm-lakes
        grid
        place-items-center
        '
          >
            <Button
              color='lightBlue'
              buttonType='filled'
              size='regular'
              rounded={false}
              block={false}
              iconOnly={false}
              className='flex items-center space-x-2'
            >
              <Icon name='add' size='3xl' />
              <h2 className='capitalize text-lg font-google-sans font-medium'>
                Create
              </h2>
            </Button>
          </div>
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
          <BlogPost />
        </main>
      </div>
    </div>
  )
}
